name: CI Pipeline

on:
  push:
    branches:
      - main
# pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

        # ----------------  API - PYTHON LINT TEST  ---------------- #

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
#          cache: 'pip'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8 on project
        run: flake8 --exclude=__pycache__,node_modules .
        # run: flake8 --exclude=.git,__pycache__,.venv,.env,.mypy_cache,.pytest_cache,node_modules .

        # ----------------  FRONTEND ES LINT TEST ---------------- #
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'
#          cache: 'npm'

      - name: Install eslint with other packages
        run: |
          cd frontend
          npm install

      - name: Run eslint
        run: |
          cd frontend
          npm run lint # configured in package.json

      # ---------------- DOCKERFILE LINT TEST ---------------- #

      - name: Install Hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
          chmod +x hadolint

      - name: Run Hadolint
        run: ./hadolint api/Dockerfile worker/Dockerfile frontend/Dockerfile
        # run: ./hadolint --ignore DL3018 --ignore DL3015 --ignore DL3008 api/Dockerfile worker/Dockerfile frontend/Dockerfile
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
#          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

      - name: Test with pytest
        run: |
          pytest --cov=api --cov-report=xml --cov-fail-under=85
#          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
  build:
    needs: test
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - '5000:5000'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set SHA
        run: echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          
          
      # ---------------- API ----------------
      - name: Build API image
        run: |
          docker build -t api ./api

      - name: Tag API image
        run: |
         docker tag api localhost:5000/api:latest
         docker tag api localhost:5000/api:${GIT_SHA}

      - name: Push API image
        run: |
         docker push localhost:5000/api:latest
         docker push localhost:5000/api:${GIT_SHA}

      # ---------------- WORKER ----------------
      - name: Build Worker image
        run: |
         docker build -t worker ./worker

      - name: Tag Worker image
        run: |
         docker tag worker localhost:5000/worker:latest
         docker tag worker localhost:5000/worker:${GIT_SHA}

      - name: Push Worker image
        run: |
         docker push localhost:5000/worker:latest
         docker push localhost:5000/worker:${GIT_SHA}

      # ---------------- FRONTEND ----------------
      - name: Build Frontend image
        run: |
         docker build -t frontend ./frontend

      - name: Tag Frontend image
        run: |
         docker tag frontend localhost:5000/frontend:latest
         docker tag frontend localhost:5000/frontend:${GIT_SHA}

      - name: Push Frontend image
        run: |
         docker push localhost:5000/frontend:latest
         docker push localhost:5000/frontend:${GIT_SHA}
  scan:
    needs: build

    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - '5000:5000'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set SHA
        run: echo "GIT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # ---------------- API ----------------
      - name: Build API image
        run: |
          docker build -t api ./api

      - name: Tag API image
        run: |
          docker tag api localhost:5000/api:latest
          docker tag api localhost:5000/api:${GIT_SHA}

      - name: Push API image
        run: |
          docker push localhost:5000/api:latest
          docker push localhost:5000/api:${GIT_SHA}

      # ---------------- WORKER ----------------
      - name: Build Worker image
        run: |
          docker build -t worker ./worker

      - name: Tag Worker image
        run: |
          docker tag worker localhost:5000/worker:latest
          docker tag worker localhost:5000/worker:${GIT_SHA}

      - name: Push Worker image
        run: |
          docker push localhost:5000/worker:latest
          docker push localhost:5000/worker:${GIT_SHA}

      # ---------------- FRONTEND ----------------
      - name: Build Frontend image
        run: |
          docker build -t frontend ./frontend

      - name: Tag Frontend image
        run: |
          docker tag frontend localhost:5000/frontend:latest
          docker tag frontend localhost:5000/frontend:${GIT_SHA}

      - name: Push Frontend image
        run: |
          docker push localhost:5000/frontend:latest
          docker push localhost:5000/frontend:${GIT_SHA}

      - name: Wait for registry
        run: |
          for i in {1..10}; do
          curl -s http://localhost:5000/v2/ && break
          sleep 2
          done

      - name: Pull images
        run: |
          docker pull localhost:5000/api:${GIT_SHA}
          docker pull localhost:5000/frontend:${GIT_SHA}
          docker pull localhost:5000/worker:${GIT_SHA}

      # ---------------- API ----------------
      - name: Scan API image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: localhost:5000/api:${GIT_SHA}
          format: 'sarif'
          output: 'api-trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL'

      - name: Upload API scan results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: api-trivy-results.sarif

      # ---------------- FRONTEND ----------------
      - name: Scan FRONTEND image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: localhost:5000/frontend:${GIT_SHA}
          format: 'sarif'
          output: 'frontend-trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL'

      - name: Upload Frontend scan results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: frontend-trivy-results.sarif

      # ---------------- WORKER ----------------
      - name: Scan WORKER image
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: localhost:5000/worker:${GIT_SHA}
          format: 'sarif'
          output: 'worker-trivy-results.sarif'
          exit-code: '1'
          severity: 'CRITICAL'

      - name: Upload Worker scan results
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: worker-trivy-results.sarif
